### ISSUE TITLE
Ajout d'un cheminement

### ISSUE THREAD

**Issue by arezkismail** [arezkismail/firefox-hotel#1]
tracer un chemin à partir de ma position jusqu'à l'hotel le plus proche.
il faut donc regrouper le code des deux fichiers : myPosition et allHotels.

**Comment by KarloGl** [comment]
j'ai intégré la position actuelle dans le fichier allHotels, donc plus besoin de MyPosition. J'ai fait l'acheminement aussi. ferme l'issue

**Comment by arezkismail** [comment]
c'est fait
